### ISSUE TITLE
PMMP Wiki Japanについて

### ISSUE THREAD

**Issue by ikatyo** [MCBE-JPN/mcbe-jpn.github.io#3]
[PMMP Wiki Japan](http://pmwiki.tech)ですが、Deprecated - 非推奨カテに移動する事を提案します。

理由
・編集員が少なすぎる/アクティブな編集員が数名しかいない
MediaWikiの編集形式が複雑すぎて殆どの人が編集員申請をしてこない背景があり
→結果、過疎状態な上に情報が古すぎて参考になるかが怪しい

・運営者が失踪気味
運営者が留学に行ってたりで管理できておらず、現在はikatyoが代理運営者(管理者)ですが、その代理運営者も忙しく、全く管理が出来ていません。

以上

**Comment by kazuemon** [comment]
了解しました。
修正しておきます。
