### ISSUE TITLE
ページ統合

### ISSUE THREAD

**Issue by kazuemon** [MCBE-JPN/mcbe-jpn.github.io#6]
この2つを統合できないかと思ってます

https://github.com/MCBE-JPN/mcbe-jpn.github.io/blob/master/about.md
https://github.com/MCBE-JPN/mcbe-jpn.github.io/blob/master/notice/to-mcbe-jpn-developpers.md

**Comment by fujiwaraizuho** [comment]
統合しちゃいましょう
